env:
  global:
    - secure: 2ot66q0PaKKB3tlDUwck8LVuSu4cGDywXD0rhLRC0JSJ+TZ1t4zHMa+IL6N+EgftTBVqz54MyKGS/qaM3IbU2ClkbwK7v6SQOJ943lSWXe7mDHnwsrnje7F1DiNZtGqjn3L4IFcBS5XTHWz7DYavdxC7G2XJ0xc9hbeV0ZwE2Plp8uZpqDGYxDRhliPZliGO0iIZITlEsoU3OIHuXFqL+h/+cPEGmwjNtbAQc0Lcl3tJjX+GUB+z6hYrOdwyE18ee1zkKpe3GuIBRIE851rZVu3YSqNRtLEut9HgqGUzlSDhMz3ogeQTbYdA6kuPZv11YBmL9ls4uUcgusaQKinuE93sF603u02WIFVzFYbz58LBRtZHIzd+J+BzccLGfUr81KkDQm/LIFJnGXlxpi6MXBQsUzrNmqvF1VFZ7Oy0YF7L1IV80ULF4GnVQPnwfnf3OsmgWGExXqEWNFhOErKn+JmE/0h3GVvoSt8N6XHLWVVy3pgnLKYMq0OsAhnR8CKxZdeCFjx6hBdcuYLsTJCttOqbOby2CGpY2aQDhTfbuT7pn+2MoUGNI5WO6NKEGcEwnxIpmCVIdS+K06WjOTWMgVS2Qs2Vy6+4SOLqO1x6WrNd+Qtljz+hDKFfaIUKJXU+NAWtrnuN+d2v6xSBGaX4f27MOpZ1iWfwMEuQSdrmKAw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
