env:
  global:
    - secure: IdEm7lDiw9Af/vD3l6/nGRJ5dwP19qboX4jEYBfZqVC+WDNMJlJB7tNDvRaULf262O88qDjzntp/6FvFBx761lahtfIwGrxQVFeCf6SmvZv2rEy5WoNCqoFOFSDX07Yuqrqf/Sxk8BX/K39/cVVTRLFWOl18mU2V4CZGLrgL9wChJIxfTSQZjyAniJ2QUSG9+rkcD/LT3qvyLBZ8wk3ONIoT/Dk8dSZdODzIJgJDifRgsO566syREPExBT1KqNrcSF+txkruNtfUUaE7Af3Lzk5CyirlrihGNrJtR69gzRQTWeTtkIiGWcUjD9pPl5sINEaQ6aTOg+R021CbtpjO8WdfsdeoEr1NcsH2LSv+fxZLKStOQedXmNWMxIi3joYrafWnXyNCSc9Ud9IBHrHd+OoukFbu1S21L9v17Xo7z0m9zaD015wwq8A+jUPRQJUuqSBw4g+BKEZdLUdiA/SXl8T/KMsMT7AhxJ3GUK8lbeGtT8kkqUhkuDStry/qh5ikzlzIKBGgnUUQpAQjtHclQi4AAS00RfSRyT27akKxs8EP0+yMqx6VEeudafJnFU13pPhr9j7uECa22ETlGq3w80nfwA8s7hJfGltT+63ZWjaGYMBrJzgxHynB9Rp3/pQW5iQd1/sABW6hFG0RFXtoLND7KGYH13oUbXiT7uwahUM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
