env:
  global:
    - secure: wE/Qz1L+pa7h8ODSHSd9T4V2vg7nLAFhA/pfZS6MXQiYz+oY2ROqDRk1/OD2cateiAYeXBOk5WK0gshWQdYwzsOTEcVYkp2boSOqhtFlNjWOCk/a/Tx7ISH41bJCL6Le48e7hbS2cBD26h6xc2eY/SWlsKBlMVYXyZsHlwvpOYccxgbTPqikIFk03kQ4YOwixG/AQzp2PEOxvkbw23aOXPfFbFrU/PMjEqFiIE5fBZs4fW+dUDksZXAcP/sTMD15GnHSKVM0Yv4vQ3Bt/LFgeYqaYD8tms0pzobpw8nKSgGRMYPP52byyAWBEVmu3oJZqf98j/R8FCcLMo3oa7t5pkXCZadkHq7+74y0Oneb+BDjN3/ZZXBeYuRsyFIWR/taehVmgurJmDRM8mO/qpJccixwQBU4KqwvULScnCeDUh0hdiWuQ1u5TLWhXIh7Glz25mRB0Ix/PyG4SM8mroTrqkdTeSZq7SrJKgavKOD9ALpf3XGW/I84zOfduGlGnnvqk6apXkImTN3s6/QtMt+uoJ6iKxj0oOyqTUJ+ZQx4I4sj7LK345EZ7pKPRs8PXUQhdBvqgfS97gjxZ7+QyAQ2J0+wzWy1YKsMRl2mrjkKUx5SENBKLvY53+Rwn676k27B5kz4v26TE2kMk7q4w0biPcHdjX1ltlsGR+CzRxvrlmA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
