env:
  global:
    - secure: bGN8Lhl/ngoQ4BITPoTceaZX6kJyiXaC2ejVdDFsjYjX+ElkGfyS8qSMekLKD5i0/IUlkL1KyEFRysTAiyKty2iftLrjnCXgP+kuePF1Ng/hdfQWMmWCmpdsbUwXD49MN0VEEOTVyuyY+4xrh+yF8Vz730beEYlyNUAhtHfnmDSW12r+Mn6xLqsj5ia1ZYhXRLT6lSXtnGFdVeAEe9BAs/IDxOA1fXwPRciv6cIGnSi3ykWzEpxdg+LRv0Ot1qVfOAfq6Vari5yACq1OoKivwAwkwNSQApUQ7rO71rJP6BmkWBok73DZwN2LmnVG+jmwq+fKpBBrnIj8UlVnTe7lHjr04VHMx0HtrD3aoPIJ4yrYvffaupVzan6HJmYQhdivyVj57Oo8nvNhCO8XOz++5+JMIpeLjzqrG6BcPN1FJw2Uom31C7x/p8RDf2C5WJc1+AEmCPOo+hgjwyIvHmdE4dg3WndwRHoAMOEoQ5I4R1ZAf5IIiupZgS2Ok1ZLXnLSpZ7obbIECMLfgW8fqRVRO0l4dfNXwYFU8QrC1l36E5n3E6QjDHBKzv4gIuy6WZe065hnOKGjPqEadYJFUQ2YhleT0OiaGydSwt6vtctOlMeKXfxouH9yXi2iX1LOjmMTjHWBH/CzX+sDynCGOR8qGmhgchcza2Cl/t7vXo9eLmM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
