env:
  global:
    - secure: a4QJq28SJC+e55ksGIODrbE6wp/j/dMuuzEZSFhwS/x8mWm0xCKi0NTKUCT12pyIMzq3yxEi0U0YIdLVap3n6swyokxZQvdfXGrXtQBwn7xGhzz2pW4qZRLiMi32n6bESUwax8NeCki6caPbPOvNYZ0nJ/IfmAas6dgKYUEkSKayRoeqsoET7hZSNFOGBg5dteTb8sxteCrNPKZduPRUcphOx/mYMkfGDlc8wDdGQS8egP3qcG0qb53q8Fwd6H49+mVmDWOYF/T3X//Ncju8j/rC5pkVd3IIWh6R4Q7hFWLgbm0oz1j1vEouNPul/0P6VdYA+jpi3jCIXIrBMMfIZPLoLKU0RYTE8FKS1zvrXwFNZtQ+d7vdZx1RlcjJzbi21fX3v8c3vQpsgk1EVoszUbmM/L5AWaGBqLz1NONOX51UDWsfmzU5sXy3hPWz5J/R0RgGFOmzjlmw5xTOrpWRJnGURTW6/wsXAwYR/YwPiQF8H6StED8whE/iJHRHKJnPPx4N6hwTU4Ho2d+qgGQLI9gXvl8f1LB5DrWsdyq0JkWJANx0YymOZQVxQt2ahBv4NM46hXNVjIw0ykwhFm/oSNC1AQI/hCthdHH9KXzFBWCIdnMhjHAO4QoyE1FGQKG2WVWnRHcOX6NDn9UzgpRJ+myjdz/7RgZm1OKgvFiX4ZM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
