env:
  global:
    - secure: RjQVoUbcPhyovihxZ35cKi6pu6lKSBWKMzGzVqAlAl8fhMOKk0Ufs9bX1xKtWEdvCyQWI0aDCVzaaKv11j3YCowbnAVsbVJbUsdoeS+Yl8EPOicLALoVqdmb9oehiAOWWPLdfbXZ7vl05h7BsuxOAm8W+mWZg4FaRXiuAbg1C2L7r/4wgqD2kGi6Og6adxUzgx07f/8pRjMzX8GyuVbilNTEZSNBjpx/RLsg2Yga3L5wcdl7Qnvzp5Y9ipqi9kBFLeXYteV3zR/xggkpBIkfeaHrfsg+zNh1ccVnYk6EWG5h/DXCHLLWy6qy0IetqKXPaxBgy5WkX+h19sfWr9GQ04RCG1zPKZdX4iURSlUyRg4w9Uw51Hd7QhBE1u4UIK9yuAMt6gQaPAW3bgNEuHhz7h4IC3/Xr9FwXct3lXLgqZsmJbdoW+Z4U0QHBOtg8rv2S+H3yp8UUYa7lCLS/j7JSB+LG/vr0jGhQTb/+1P52V/Cgeu8je4NF71wmm6uptzwPHrQGL7mYgYo6sEsFy7ElWtTfvj4v/FtGxlP52MdDUIKQgL9wPHwOU73a8YGKHbZqorwHUt1F5NxAx1b5z6SJA17UwhSQx6pZrlZD+q9pGx/TIys0LSiRkulLa5JEdm2YFFLC6uvGgqqvs9aV3CApRiPUtP6gzPsZEfdhy2w49Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
