env:
  global:
    - secure: Wg6QrO7VXSrRlqLoGBl2/yWSAdXZe2jaotLkxAJiV0dU3/1nnse7twJWUM6XNlf1U4qG5FzWBfZpEhYm/9YHIYP+0+KN0VTq90Oxn/Txtpzxebmyw/S5nLwGZsT9dHtmxTQAVi74i0B3617WlIaJ8YbPx9k6SlAXgtVJ3IjVNmkgwUpwxdDEMRXR6dMIsiohN6Ww1OQfM7fj98GMyOA3So3hxc/S1x+yhJUVNZuMgG4oM0Hd6rj8mmCg1jAf4FA1wDTV8XMMROEodStdBMIEae9hyDHiVfNExu/4ftSfSPThAR7lsd2E6mceOAuL7LWqMeDLgMR23jXynBIZgz+I1wcnCQxHjGt5R00sn9JQx4qeRtRWLhy6/UjQk+hIA/oAwzrX5GaKrE0q1MOcBAQrsUs5HQ1cZy8/3uIm9oJvsUw/2vOuzTLvVoOZOTT0UpoM6mFKxO1ryXbZMeotUZ0ysH01BHNUP1gdjn/jwuGBfI2ndDb4T0Xt4tQXEQhzbm0xAoPY0rdtyEq4pYywywrUsS0S5X3LPFrj/2paMWp5DQlPjKcAary9REOPld9MOuoUHPn+IkLzh+2j/gPzAXCsOukldcm9zwvg+uDQVTjnP4L4n0qkJQcDP+XoxRSePGlC7SVsQQpSbVtO1U2y0tGFIsNzCldnkuM0vu8hClYBeEA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeusTracker_abuse.ch
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
